name: CI

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    Tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: yarn

            - name: Install dependancies
              run: yarn install --frozen-lockfile --immutable

            - name: eslint
              run: yarn lint

            - name: Build
              run: yarn build

    Deploy:
        needs: Tests
        if: github.ref == 'refs/heads/main'
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: yarn

            # Setup React and build
            - name: Install dependancies
              run: yarn install --frozen-lockfile --immutable

            - name: React Build
              run: yarn build

            #  Setup docker build and push
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: blackshadev/littledivelogapp:latest

            # Update portainer image
            - name: Update server image
              uses: satak/webrequest-action@v1.2.4
              with:
                  url: ${{ secrets.PORTAINER_WEB_HOOK }}
                  method: POST
